### ISSUE TITLE
Update response from get_one_band

### ISSUE THREAD

**Issue by MaxRickettsUy** [seancrim23/metal_archives_2_back#1]
Currently the get_one_band endpoint returns a list of releases with the band info in each item.

```
[
  { name: foo, releaseId: 1, ...},
  { name: foo, releaseId: 2, ...}
]
```

Could we instead return an object like:

```
  {
    name: foo,
   ...other band info,
   releases: [ ... ]
}
```
This way on loading a band page I can extract the band info directly and then loop through the releases to build everything else.

**Comment by seancrim23** [comment]
updated to unpack the sql response into a friendlier format:

`http://localhost:5000/band/1`

`{"name": "cool band", "status": "active", "band_picture": "band_pic_location", "releases": [{"release_id": 1, "year": 1997, "name": "cool band", "review_avg": 7.333333333333333, "review_count": 3}, {"release_id": 2, "year": 2000, "name": "cool band", "review_avg": 31.0, "review_count": 4}, {"release_id": 3, "year": 2001, "name": "cool band", "review_avg": 11.0, "review_count": 1}]}`

pls pull my changes, i just pushed into main, lmk if its weird at all

**Comment by MaxRickettsUy** [comment]
Looks great 👍🏻 Can we add `members` to `Band` ?

**Comment by seancrim23** [comment]
can we close this issue? i think adding members to band should be a feature rather than staying on this issue since the initial reason for opening has been fixed up

**Comment by MaxRickettsUy** [comment]
🫡
